import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/cyber/ThemeContext";
import ThemedBackground from "../components/cyber/ThemedBackground";
import ScrollProgress from "../components/cyber/ScrollProgress";
import BootLoader from "../components/cyber/BootLoader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Usman Shehzad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="_zZHAOBJcpHtWpBg5Y4SBt559fcpKEu2OI_t-x1dxnc" />
        <link rel="icon" type="image/png" href="/favico.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <BootLoader />
          <ThemedBackground />
          <ScrollProgress />
          <div className="relative z-10">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
